# Generated by Django 3.2.8 on 2021-10-11 11:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date_of_creation", models.DateTimeField(auto_created=True)),
                ("Title", models.CharField(default="No Title", max_length=255)),
                (
                    "Identifier",
                    models.CharField(default="No SEO Optimized tag", max_length=140),
                ),
                ("UUID", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("SubTitle", models.CharField(default="No SubTitle", max_length=255)),
                ("Content", models.TextField()),
                ("URL", models.URLField()),
            ],
        ),
    ]
