# Generated by Django 3.2.8 on 2021-10-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtable',
            name='Date_of_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
