# Generated by Django 3.2.7 on 2021-10-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logic", "0002_blogtable_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogtable",
            name="Identifier",
            field=models.CharField(default="No SEO Optimized tag", max_length=140),
        ),
    ]
